#!/bin/bash

# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook looks for
# files with "apikey" and "password" strings and shows a warning

flags=$(git diff --no-ext-diff --staged | egrep -i --count "apikey|password")
if [ "$flags" -ne "0" ]; then
   echo "WARNING! You are attempting to commit sensitive data from:"
   git diff --no-ext-diff --staged --name-only -i -G "apikey|password" | sed 's/^/\t* /'
   echo -e "\nUnstage relevant hunks with"
   echo -e "\tgit reset --patch'"
   exit 1 
fi
